name       : kconfig
version    : 5.85.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.85/kconfig-5.85.0.tar.xz : bad5482894d3dcf8bf213217c0a8bb7baba3803a737befcecaf83cda23dab962
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - MIT
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %patch -p1 -i $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
