name       : kconfig
version    : 5.70.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/kconfig-5.70.0.tar.xz : 3679034b2f4b637caa0c87eec9487aa8431fe43246bac84842801d7e1d2470e8
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
