name       : kconfig
version    : 5.52.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/kconfig-5.52.0.tar.xz : 1da21c1cbeae28e4faa850baaab94c6a86c80f86db486c811f3764da82ba428b
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
