name       : kconfig
version    : 5.44.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kconfig-5.44.0.tar.xz : b5b2b3cb0f8e773b7537a09cc4e6bdbe37e0884acb8e60dc8488670a993cd4ed
license    : LGPL-2.1
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
