name       : kconfig
version    : 5.35.0
release    : 4
source     :
    - https://download.kde.org/stable/frameworks/5.35/kconfig-5.35.0.tar.xz : abbf1156c4ff67a0b45dee67f97683fb11295bdbb26d76c8b08bc7d9b26e71cf
license    : LGPL-2.1
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
