name       : kconfig
version    : 5.65.0
release    : 35
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/kconfig-5.65.0.tar.xz : 8dfa064effdf559e1179e9d7e5ec12ff9d79fcfef1859bd1793557261e94a6ed
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
