name       : kconfig
version    : 5.71.0
release    : 41
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.71/kconfig-5.71.0.tar.xz : 618ff0d168abf8fb73dc83431b9a76f7859d522bea100ff07c7e1632e129e3f4
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
