name       : kconfig
version    : 5.66.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/kconfig-5.66.0.tar.xz : c0df73bde40162a5ffc20604c2ad343e71a6df852c3f7b05e70e1464f5f63256
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
