name       : kconfig
version    : 5.42.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/kconfig-5.42.0.tar.xz : b8e5889989354fef6c52e7a9f40e6260382fe6bfcda3da3d3c3201064403ef21
license    : LGPL-2.1
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
