name       : kconfig
version    : 5.39.0
release    : 7
source     :
    - https://download.kde.org/stable/frameworks/5.39/kconfig-5.39.0.tar.xz : 3c504d69a38d7fa2e89dbe15b8c02d0803be20f3907c86f18be090031c223104
license    : LGPL-2.1
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
