name       : kconfig
version    : 5.60.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kconfig-5.60.0.tar.xz : 541acceead9ca516e3562109e7e94351ce378c234bea968c8dfde78f00559233
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
