name       : kconfig
version    : 5.47.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kconfig-5.47.0.tar.xz : d882255769ab95d49d4df4b40e659b25754935206b1fc07310e2cbc34d3cdb45
license    : LGPL-2.1
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
