name       : kconfig
version    : 5.40.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kconfig-5.40.0.tar.xz : 6b96654c525de124fe127f4d40e0ff8e99a1d31ef7b368de7ce3af876b55295f
license    : LGPL-2.1
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
