name       : kconfig
version    : 5.68.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/kconfig-5.68.0.tar.xz : c3bf138a7a4d002475f2483987baf40a61cda7d491c3cc292dd2c6da726ee898
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
