name       : kconfig
version    : 5.55.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/kconfig-5.55.0.tar.xz : 4a566842d566e9904d1478fa428cbf8b1caf49efe142ae237f24a4c16e64fa19
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
