name       : kconfig
version    : 5.43.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/kconfig-5.43.0.tar.xz : 22ebe055ae6545e01653b2e7d678145261cc5073202561735a894aa59b5841d9
license    : LGPL-2.1
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
