name       : kconfig
version    : 5.51.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kconfig-5.51.0.tar.xz : 78b11737356f09c316bfe00f0fc1fa70255b7f03fab7e3a84660757c4a57f1c0
license    : LGPL-2.1
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
