name       : kconfig
version    : 5.28.0
release    : 2
source     :
    - http://download.kde.org/stable/frameworks/5.28/kconfig-5.28.0.tar.xz : fe9bf24e8ec3492a7e440fae2c01cc00565f69541cd16876879103843656ba4d
license    : LGPL-2.1
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
