name       : kconfig
version    : 5.74.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kconfig-5.74.0.tar.xz : dfeff0649f8987f88a01827c06468b87547509d9e46920902a55f6a0d6adc5db
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
