name       : kconfig
version    : 5.54.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kconfig-5.54.0.tar.xz : e7b6023db1655b542ede2e0f598ca59551c04dff4ed6b178d31531022ae0e492
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
