name       : kconfig
version    : 5.59.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kconfig-5.59.0.tar.xz : 28aac471e6960636afbcbd525b88b4f186180e23a76c140f48d256a7a9e1254a
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
