name       : kconfig
version    : 5.64.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kconfig-5.64.0.tar.xz : 112c1db9f038dbacf357d08645c83ca103d8c3e7fb0c880ac16f665fdf7d9157
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
