name       : kconfig
version    : 5.94.0
release    : 63
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.94/kconfig-5.94.0.tar.xz : 8e6d9104f070d94f083be000ea116acae3499b0dd110fa4c9c55f51ea91cb3d7
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - MIT
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %patch -p1 -i $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
