name       : kconfig
version    : 5.56.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/kconfig-5.56.0.tar.xz : 2a970733da16b90ecc317e8ac77f08530650eb2e98dc93834e09e156ec353172
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
