name       : kconfig
version    : 5.36.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.36/kconfig-5.36.0.tar.xz : b31e3a8595fa8dc14aa0b1828633c712205097a6e3d14650ae813d4d7833d654
license    : LGPL-2.1
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
