name       : kconfig
version    : 5.58.0
release    : 27
source     :
    - https://download.kde.org/stable/frameworks/5.58/kconfig-5.58.0.tar.xz : 6f464a63079f43f11deb7f1661dadaa12539b8a8c75e3fa7476dae8ab6886a5e
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
optimize   : lto
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Avoid-unnecessary-stat-calls.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
