name       : kconfig
version    : 5.32.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.32/kconfig-5.32.0.tar.xz : b79d14ddee564f8876cd75e67d95e4266ff253cce55073a12e292d04688052dd
license    : LGPL-2.1
component  : desktop.library
summary    : Persistent platform-independent application settings.
description: |
    Persistent platform-independent application settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
